version: "3.8"

services: 
 web:
  image: nginx-app-web
  deploy:
    replicas: 3
  ports:
   - 8080:80
  volumes:
   - "/home/vagrant/BGAppDockerExercise/web:/var/www/html:ro"
  networks:
   - app-network

 db:
  image: mariadb-php-db
  networks:
   - app-network
  environment:
    MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"


networks:
   app-network:
