version: "3.8"

services:
 
 web:
  image: westfy/nginx-web-app
  deploy:
     replices: 2
  ports:
   - 8080:80
  volumes:
   - "/home/vagrant/BGAppDockerExercise/web:/var/www/html:ro"
  networks:
   - app-network

 db:
  image: westfy/mariadb-db-app
  networks:
   - app-network
  environment:
    MYSQL_ROOT_PASSWORD: 12345


networks:
   app-network:
